# Generated by Django 2.1.2 on 2018-10-29 09:59

import content.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSupplies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(blank=True, null=True, upload_to=content.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('warehouse_proc_time', models.DateTimeField()),
                ('dispatch_queue_time', models.DateTimeField()),
                ('dispatched_time', models.DateTimeField()),
                ('delivered_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_supplies', models.ManyToManyField(to='content.MedicalSupplies')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Order')),
            ],
        ),
    ]
