# Generated by Django 2.1.2 on 2018-10-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20181029_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalsupplies',
            options={'verbose_name_plural': 'medical supplies'},
        ),
    ]
