# Generated by Django 2.1.2 on 2018-10-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181029_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalsupplies',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Type'),
        ),
    ]
